// <auto-generated>
// Rewired Constants
// This list was generated on 7/10/2019 3:58:34 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveX")]
        public const int MoveX = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveY")]
        public const int MoveY = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LookX")]
        public const int LookX = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LookY")]
        public const int LookY = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump")]
        public const int Jump = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Switch")]
        public const int Switch = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Select")]
        public const int Select = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "PickUp")]
        public const int PickUp = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Pause")]
        public const int Pause = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Submit")]
        public const int Submit = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Sprint")]
        public const int Sprint = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Open Map")]
        public const int Map = 11;
    }
}
